### ISSUE TITLE
Missing quotation of field values

### ISSUE THREAD

**Issue by ajurcik** [alibaba/innodb-java-reader#4]
When dumping table data to a file field values can't be quoted. This becomes an issue when a string-like, e.g., `VARCHAR`, value contains chars that are used as a delimiter. When a CSV reader reads such a value it splits it into two or more *false* columns. Therefore a CSV reader encounters an unexpectedly higher count of columns.

**Comment by ajurcik** [comment]
I created #5 in order to address the issue.

**Comment by neoremind** [comment]
Good catch! Thanks for your contribution @ajurcik 😄  I addressed some comments in the PR.
